export const projects = [
  // FOUNDATIONS:
  {
    name: "Recipes Site",
    screenshot: "./screenshots/foundations/odin-recipes.png",
    description: "Basic HTML static site showcasing 3 recipes.",
    liveUrl: "https://jbentleyd-png.github.io/odin-recipes/index.html",
    repoUrl: "https://github.com/jbentleyd-png/odin-recipes",
    category: "foundations",
  },
  {
    name: "Landing Page",
    screenshot: "./screenshots/foundations/landing-page.png",
    description: "A landing page format using flexbox.",
    liveUrl: "https://jbentleyd-png.github.io/practiceLanding/",
    repoUrl: "https://github.com/jbentleyd-png/practiceLanding",
    category: "foundations",
  },
  {
    name: "Rock Paper Scissors",
    screenshot: "./screenshots/foundations/janken.png",
    description: "JS-powered Rock Paper Scissors vs your browser.",
    liveUrl: "https://jbentleyd-png.github.io/jankenpon/",
    repoUrl: "https://github.com/jbentleyd-png/jankenpon",
    category: "foundations",
  },
  {
    name: "Etch-a-Sketch",
    screenshot: "./screenshots/foundations/etch-a-sketch.png",
    description: "Using DOM manipulation to make a drawing UI.",
    liveUrl: "https://jbentleyd-png.github.io/etch-a-sketch/",
    repoUrl: "https://github.com/jbentleyd-png/etch-a-sketch",
    category: "foundations",
  },
  {
    name: "Calculator",
    screenshot: "./screenshots/foundations/calculator.png",
    description: "JS-powered calculator that takes ENG and JP input.",
    liveUrl: "https://jbentleyd-png.github.io/calculator/",
    repoUrl: "https://github.com/jbentleyd-png/calculator",
    category: "foundations",
  },

  // RUBY:
  {
    name: "Basic Ruby Puzzles",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Four mini-projects solving beginner CS problems.",
    liveUrl: "./demos/ruby/basics.html",
    repoUrl: "https://github.com/jbentleyd-png/ruby_basic_projects",
    category: "ruby",
  },
  {
    name: "Tic Tac Toe",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Using OOP to create a two-player tic tac toe game.",
    liveUrl: "./demos/ruby/janken.html",
    repoUrl: "https://github.com/jbentleyd-png/tic_tac_toe",
    category: "ruby",
  },
  {
    name: "Mastermind",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Another OOP project to practice Ruby skills.",
    liveUrl: "./demos/ruby/mastermind.html",
    repoUrl: "https://github.com/jbentleyd-png/mastermind",
    category: "ruby",
  },
  {
    name: "Hangman",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Play save-able games with file serialization.",
    liveUrl: "./demos/ruby/hangman.html",
    repoUrl: "https://github.com/jbentleyd-png/hangman",
    category: "ruby",
  },
  {
    name: "Connect Four",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Built with Test-Driven Development.",
    liveUrl: "./demos/ruby/connect-four.html",
    repoUrl: "https://github.com/jbentleyd-png/tdd_connect_four",
    category: "ruby",
  },
  {
    name: "Recursion",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Creating fibonacci sequence and merge sort recursively.",
    liveUrl: "./demos/ruby/recursion.html",
    repoUrl: "https://github.com/jbentleyd-png/recursion_project",
    category: "ruby",
  },
  {
    name: "Linked Lists",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Learning about Data Structures in ruby.",
    liveUrl: "./demos/ruby/linked-lists.html",
    repoUrl: "https://github.com/jbentleyd-png/Linked-list-ruby",
    category: "ruby",
  },
  {
    name: "HashMap",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Learning more about Data Structures in ruby.",
    liveUrl: "./demos/ruby/hashmap.html",
    repoUrl: "https://github.com/jbentleyd-png/hash_map",
    category: "ruby",
  },
  {
    name: "Binary Search Tree",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "A self-balancing BST to learn DSA.",
    liveUrl: "./demos/ruby/bst.html",
    repoUrl: "https://github.com/jbentleyd-png/bst_project",
    category: "ruby",
  },
  {
    name: "Knight's Travails",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "Optimizing Knight routes across a chessboard.",
    liveUrl: "./demos/ruby/knights-travails.html",
    repoUrl: "https://github.com/jbentleyd-png/Knights_Travails",
    category: "ruby",
  },
  {
    name: "Chess",
    screenshot: "./screenshots/ruby/placeholder.png",
    description: "My capstone project for the Odin: Ruby course.",
    liveUrl: "./demos/ruby/chess.html",
    repoUrl: "https://github.com/jbentleyd-png/chess_project",
    category: "ruby",
  },

  // INTERMEDIATE HTML & CSS:
  {
    name: "Sign-Up Form",
    screenshot: "./screenshots/intermediate/form.png",
    description: "Using CSS variables to make light/dark modes on a form.",
    liveUrl: "https://jbentleyd-png.github.io/form_practice/",
    repoUrl: "https://github.com/jbentleyd-png/form_practice",
    category: "intermediate",
  },
  {
    name: "Admin Dashboard",
    screenshot: "./screenshots/intermediate/dashboard.png",
    description: "Using CSS grid to create a dashboard layout.",
    liveUrl: "https://jbentleyd-png.github.io/dashboard_practice/",
    repoUrl: "https://github.com/jbentleyd-png/dashboard_practice",
    category: "intermediate",
  },
];
