export const projects = [
  {
    name: "Recipes Site",
    screenshot: "./screenshots/odin-recipes.png",
    description: "Basic HTML static site showcasing 3 recipes.",
    liveUrl: "https://jbentleyd-png.github.io/odin-recipes/index.html",
    repoUrl: "https://github.com/jbentleyd-png/odin-recipes",
    category: "foundations",
  },
  {
    name: "Landing Page",
    screenshot: "./screenshots/landing-page.png",
    description: "A landing page format using flexbox.",
    liveUrl: "https://jbentleyd-png.github.io/practiceLanding/",
    repoUrl: "https://github.com/jbentleyd-png/practiceLanding",
    category: "foundations",
  },
  {
    name: "Rock Paper Scissors",
    screenshot: "./screenshots/janken.png",
    description: "JS-powered Rock Paper Scissors vs your browser.",
    liveUrl: "https://jbentleyd-png.github.io/jankenpon/",
    repoUrl: "https://github.com/jbentleyd-png/jankenpon",
    category: "foundations",
  },
  {
    name: "Etch-a-Sketch",
    screenshot: "./screenshots/etch-a-sketch.png",
    description: "Using DOM manipulation to make a drawing UI.",
    liveUrl: "https://jbentleyd-png.github.io/etch-a-sketch/",
    repoUrl: "https://github.com/jbentleyd-png/etch-a-sketch",
    category: "foundations",
  },
  {
    name: "Calculator",
    screenshot: "./screenshots/calculator.png",
    description: "JS-powered calculator that takes ENG and JP input.",
    liveUrl: "https://jbentleyd-png.github.io/calculator/",
    repoUrl: "https://github.com/jbentleyd-png/calculator",
    category: "foundations",
  },
];
